package com.think.greendao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.think.greendao.entity.Picture;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PICTURE".
*/
public class PictureDao extends AbstractDao<Picture, Long> {

    public static final String TABLENAME = "PICTURE";

    /**
     * Properties of entity Picture.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property PictureId = new Property(0, Long.class, "pictureId", true, "_id");
        public final static Property Url = new Property(1, String.class, "url", false, "URL");
    }


    public PictureDao(DaoConfig config) {
        super(config);
    }
    
    public PictureDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PICTURE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: pictureId
                "\"URL\" TEXT NOT NULL UNIQUE );"); // 1: url
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PICTURE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Picture entity) {
        stmt.clearBindings();
 
        Long pictureId = entity.getPictureId();
        if (pictureId != null) {
            stmt.bindLong(1, pictureId);
        }
        stmt.bindString(2, entity.getUrl());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Picture entity) {
        stmt.clearBindings();
 
        Long pictureId = entity.getPictureId();
        if (pictureId != null) {
            stmt.bindLong(1, pictureId);
        }
        stmt.bindString(2, entity.getUrl());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Picture readEntity(Cursor cursor, int offset) {
        Picture entity = new Picture( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // pictureId
            cursor.getString(offset + 1) // url
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Picture entity, int offset) {
        entity.setPictureId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUrl(cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Picture entity, long rowId) {
        entity.setPictureId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Picture entity) {
        if(entity != null) {
            return entity.getPictureId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Picture entity) {
        return entity.getPictureId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
